services:
  api:
    container_name: api
    image: project
    build: .
    command: python3 -m uvicorn project.api:app --log-config uvicorn-log.yml --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  
  worker:
    container_name: worker
    image: project
    command: python3 -m celery -A project.worker:celery_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  

  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s

  redis:
    container_name: redis
    image: redis:7
