"""v1.1

Revision ID: 1d558786b630
Revises: 3807394e17a2
Create Date: 2023-03-29 10:31:43.973559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1d558786b630"
down_revision = "3807394e17a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE taskstatus ADD VALUE 'FAILED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
